/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  THE PHOTOGRAPH CATALOGUE
 * ─────────────────────────────────────────────────────────────────────────────
 *  72 of the restaurant's own photographs, recovered from the two earlier
 *  Suan Zen builds and from their Facebook and Instagram, then described one by
 *  one so every picture carries real alt text in every language.
 *
 *  `warmth` is the thing the owner asked for: how much a picture carries the
 *  feeling of the room — guests, smiles, a full table, the chef among people —
 *  rather than a plate on its own. The site leans on the high-warmth pictures
 *  deliberately; see `peopleShots` below.
 *
 *  Files live in /public/photos, named by the SHA of their bytes, so the same
 *  photograph appearing in two places is stored once.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { L10n } from "./dictionary";

export type Photo = {
  file: string;
  category: "food" | "people" | "chef" | "interior" | "exterior" | "detail" | "signage" | "other";
  hasPeople: boolean;
  /** 0–10: how much of the restaurant's warmth this picture carries. */
  warmth: number;
  quality: number;
  orientation: "portrait" | "landscape" | "square";
  /** What the photograph shows, for a screen reader, in every language. */
  alt: L10n;
  /** Menu dishes this photograph actually shows. */
  dishMatches: string[];
  bestUse: string;
  source: "archive" | "facebook" | "instagram";
};

export const photos: Photo[] = [
  {
    file: "/photos/2ff8db8e9a7f.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Wagyu katsu with black truffle"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Two pieces of crumbed wagyu katsu topped with black truffle slices on a blue speckled plate",
      th: "วากิวคัตสึสองชิ้น วางทรัฟเฟิลดำด้านบน เสิร์ฟบนจานเซรามิกสีน้ำเงินลายจุด",
      zh: "蓝色斑点盘中两块裹面包糠的日式炸和牛排，上面铺着黑松露片",
    },
  },
  {
    file: "/photos/366b3e424e05.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 6,
    quality: 9,
    orientation: "portrait",
    dishMatches: ["Uni shokupan"],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Gloved chef's hands holding sea urchin on toasted bread with caviar while sprinkling gold flakes.",
      th: "มือเชฟสวมถุงมือสีดำถือขนมปังปิ้งหน้าไข่หอยเม่นและคาเวียร์ กำลังโรยทองคำเปลวลงด้านบน",
      zh: "戴手套的厨师双手托着放有海胆和鱼子酱的烤面包，同时撒上金箔碎",
    },
  },
  {
    file: "/photos/78893251dcbe.jpg",
    category: "interior",
    hasPeople: false,
    warmth: 2,
    quality: 9,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "counter",
    source: "facebook",
    alt: {
      en: "Curved marble sushi counter with blue chairs, painted wall murals and a blue noren at the kitchen.",
      th: "เคาน์เตอร์ซูชิหินอ่อนทรงโค้ง เก้าอี้กำมะหยี่สีน้ำเงิน ผนังภาพวาดญี่ปุ่น และผ้าโนเรนหน้าครัว",
      zh: "弧形大理石寿司吧台和蓝色座椅，墙上有手绘壁画，厨房门口挂着蓝色暖帘",
    },
  },
  {
    file: "/photos/6f879f9e50fe.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 9,
    orientation: "square",
    dishMatches: ["Salmon sushi", "Tamago", "Seasonal nigiri"],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Close-up of nigiri on a dark blue plate: salmon with roe, seared beef, white fish and tamago",
      th: "ภาพระยะใกล้ของนิงิริบนจานสีน้ำเงินเข้ม มีแซลมอนโปะไข่ปลา เนื้อย่าง ปลาเนื้อขาว และไข่หวานทามาโกะ",
      zh: "深蓝色盘中的握寿司特写：三文鱼配鱼籽、炙烤牛肉、白身鱼和玉子烧",
    },
  },
  {
    file: "/photos/389c22685003.jpg",
    category: "food",
    hasPeople: true,
    warmth: 4,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Wagyu Sun"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Gloved chef's hand holding a black plate with a wagyu-wrapped cured egg yolk topped with caviar",
      th: "มือเชฟสวมถุงมือยกจานดำ บนจานมีเนื้อวากิวห่อไข่แดงดอง แต้มคาเวียร์ด้านบน",
      zh: "戴手套的厨师手托黑色餐盘，盘中是和牛包裹的腌渍蛋黄，顶上放着鱼子酱",
    },
  },
  {
    file: "/photos/12aae199fdf8.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 7,
    quality: 9,
    orientation: "square",
    dishMatches: ["Chūtoro sushi with fresh truffle"],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Chef's bare hand holding a tuna nigiri topped with black truffle as shavings fall over it",
      th: "มือเชฟถือซูชิปลาทูน่าที่วางทรัฟเฟิลดำไว้ด้านบน ขณะโรยเกล็ดทรัฟเฟิลลงมา",
      zh: "厨师徒手托着一块铺有黑松露的金枪鱼握寿司，刨下的松露片正落在上面",
    },
  },
  {
    file: "/photos/ad61e1d47ba5.jpg",
    category: "food",
    hasPeople: true,
    warmth: 6,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Uni shokupan", "Uni"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Gloved hand holding thick toast topped with sea urchin, caviar and small purple flowers",
      th: "มือเชฟสวมถุงมือสีดำถือขนมปังชิ้นหนาที่วางอุนิ คาเวียร์ และดอกไม้สีม่วงเล็กๆ",
      zh: "戴手套的手托着厚片吐司，上面放着海胆、鱼子酱和紫色小花",
    },
  },
  {
    file: "/photos/b33e821d05b5.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Wagyu yakiniku"],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Slices of seared beef on a black hot plate with onions, mushrooms and broccoli, steam rising.",
      th: "เนื้อย่างหั่นชิ้นหนาวางบนจานร้อนสีดำ กับหอมใหญ่ เห็ด และบร็อกโคลี มีควันลอยขึ้น",
      zh: "黑色铁板上的炙烤牛肉片，配洋葱、蘑菇和西兰花，正冒着热气",
    },
  },
  {
    file: "/photos/b6e6bff9bdd4.jpg",
    category: "food",
    hasPeople: true,
    warmth: 6,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Sashimi"],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Hands hold a marble plate of sashimi while a wooden brush glazes the fish with sauce.",
      th: "มือประคองจานลายหินอ่อนใส่ซาชิมิ ขณะใช้แปรงไม้ทาซอสลงบนเนื้อปลา",
      zh: "双手端着盛有刺身的大理石盘，一把木刷正为鱼片刷上酱汁",
    },
  },
  {
    file: "/photos/c75e1799f0ce.jpg",
    category: "food",
    hasPeople: true,
    warmth: 4,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Uni"],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Gloved chef hand places a flower on four tuna nigiri topped with sea urchin, on a dark plate.",
      th: "มือเชฟสวมถุงมือใช้แหนบวางดอกไม้บนซูชิทูน่าสี่คำที่โปะหอยเม่น บนจานสีเข้ม",
      zh: "戴手套的厨师正往深色盘中四块铺有海胆的金枪鱼握寿司上放一朵花",
    },
  },
  {
    file: "/photos/d672e43a5c58.jpg",
    category: "food",
    hasPeople: false,
    warmth: 1,
    quality: 9,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Seared salmon slices on a black plate with shiso, shredded daikon, salmon roe and a yellow flower.",
      th: "แซลมอนย่างผิวสองชิ้นบนจานสีดำ วางคู่ใบชิโสะ หัวไชเท้าซอย ไข่ปลาแซลมอน และดอกเบญจมาศสีเหลือง",
      zh: "黑色盘中的炙烤三文鱼片，配紫苏叶、白萝卜丝、三文鱼籽和一朵黄色的花",
    },
  },
  {
    file: "/photos/e55b74c7148c.jpg",
    category: "food",
    hasPeople: true,
    warmth: 4,
    quality: 9,
    orientation: "landscape",
    dishMatches: ["Matcha mousse with crumble"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Two hands hold a white bowl with green matcha mousse, dark crumble and orange flowers.",
      th: "สองมือประคองจานขาวที่มีมูสมัทฉะสีเขียว โรยครัมเบิลช็อกโกแลต และแต่งด้วยดอกไม้สีส้ม",
      zh: "双手捧着一只白碗，碗中是绿色抹茶慕斯、深色酥粒和橙色花朵",
    },
  },
  {
    file: "/photos/88269e7643db.jpg",
    category: "exterior",
    hasPeople: false,
    warmth: 5,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "hero",
    source: "instagram",
    alt: {
      en: "Suan Zen Omakase at dusk: lit yellow sign, wooden building and willow trees above the car park.",
      th: "ร้าน Suan Zen Omakase ช่วงพลบค่ำ ป้ายไฟสีเหลือง อาคารไม้ และต้นไม้ริมลานจอดรถ",
      zh: "黄昏时的 Suan Zen Omakase：亮灯的黄色招牌、木质建筑，以及停车场上方的柳树",
    },
  },
  {
    file: "/photos/8f693dfc3438.jpg",
    category: "signage",
    hasPeople: false,
    warmth: 4,
    quality: 8,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "after-dark",
    source: "archive",
    alt: {
      en: "Lit Suan Zen Omakase signpost at night listing omakase seating times and izakaya bar hours.",
      th: "ป้ายไฟร้าน Suan Zen Omakase ตอนกลางคืน บอกรอบโอมากาเสะและเวลาเปิดอิซากายะบาร์",
      zh: "夜间亮灯的 Suan Zen Omakase 指示牌，写有 Omakase 用餐时段和居酒屋营业时间",
    },
  },
  {
    file: "/photos/0290e94ce2e9.jpg",
    category: "food",
    hasPeople: true,
    warmth: 5,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Sashimi"],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Gloved chef's hands plating slices of raw fish in a green glass bowl with red seaweed and a yellow flower",
      th: "มือเชฟสวมถุงมือกำลังใช้แหนบจัดซาชิมิปลาดิบหลายชนิดลงในถ้วยแก้วสีเขียวทอง ตกแต่งด้วยสาหร่ายแดง ใบชิโสะ และดอกเบญจมาศสีเหลือง",
      zh: "戴手套的厨师双手将生鱼片摆入绿色玻璃碗，配红色海藻和一朵黄色的花",
    },
  },
  {
    file: "/photos/0d393fd3d14f.jpg",
    category: "food",
    hasPeople: false,
    warmth: 1,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Layered dessert in a small glass with matcha cream, crumb base and whipped cream, on a wooden board",
      th: "ของหวานในแก้วใบเล็ก เรียงชั้นคุกกี้บด ครีมมัทฉะ และวิปครีมโรยผงมัทฉะ วางบนถาดไม้คู่กับดอกไม้สีแดงและชมพู",
      zh: "木板上的一小杯分层甜品，有抹茶奶油、酥粒底和打发奶油",
    },
  },
  {
    file: "/photos/5470cc5c5073.jpg",
    category: "interior",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Curved sushi counter with blue velvet chairs, wood-slat wall and a blue noren curtain behind it.",
      th: "เคาน์เตอร์ซูชิทรงโค้ง เก้าอี้กำมะหยี่สีน้ำเงิน ผนังไม้ระแนง และผ้าโนเรนสีน้ำเงินด้านหลัง",
      zh: "弧形寿司吧台，配蓝色丝绒座椅，后方是木条墙和蓝色暖帘",
    },
  },
  {
    file: "/photos/5d27adc7cdfe.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 8,
    quality: 8,
    orientation: "square",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "facebook",
    alt: {
      en: "Seven staff behind the sushi counter, the head chef smiling in the centre with arms crossed.",
      th: "ทีมงานเจ็ดคนยืนอยู่หลังเคาน์เตอร์ซูชิ เชฟใหญ่ยืนกอดอกยิ้มอยู่ตรงกลาง",
      zh: "七位员工站在寿司吧台后，主厨居中，双手抱胸，面带微笑",
    },
  },
  {
    file: "/photos/28ac22598eee.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Layered dessert shots in small glasses on flower-shaped wooden trays with edible flowers",
      th: "ของหวานในแก้วช็อตเรียงเป็นชั้น วางบนจานไม้รูปดอกไม้ ตกแต่งด้วยดอกไม้กินได้",
      zh: "花形木托盘上的小杯分层甜品，点缀着食用花",
    },
  },
  {
    file: "/photos/2fe08ecfcc98.jpg",
    category: "food",
    hasPeople: false,
    warmth: 4,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Wagyu yakiniku"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Sliced grilled wagyu steaming on a hot black plate with onions, mushrooms, broccoli and carrot",
      th: "เนื้อวากิวย่างหั่นชิ้น เสิร์ฟร้อน ๆ บนจานดำ พร้อมหอมใหญ่ เห็ด บรอกโคลี และแครอต",
      zh: "黑色铁板上冒着热气的烤和牛片，配洋葱、蘑菇、西兰花和胡萝卜",
    },
  },
  {
    file: "/photos/35e5b6674f55.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "portrait",
    dishMatches: ["Uni"],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Wooden trays of fresh sea urchin roe lined up in a row on a marble counter.",
      th: "ถาดไม้ใส่ไข่หอยเม่นสดเรียงต่อกันเป็นแถวยาวบนเคาน์เตอร์หินอ่อน",
      zh: "大理石台面上一字排开的木盒新鲜海胆",
    },
  },
  {
    file: "/photos/765a5e444077.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 6,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Uni"],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Gloved hands use tweezers to lift a piece of sea urchin roe from a wooden tray packed with uni.",
      th: "มือเชฟสวมถุงมือสีดำใช้แหนบคีบไข่หอยเม่นออกจากลังไม้ที่เรียงอุนิไว้เต็ม",
      zh: "戴手套的双手用镊子从装满海胆的木盒中夹起一块海胆",
    },
  },
  {
    file: "/photos/64dbf648009a.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "portrait",
    dishMatches: ["Uni"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Wooden trays packed with rows of orange sea urchin roe on a marble counter, rock garden behind",
      th: "กล่องไม้ใส่อุนิเรียงเต็มวางไล่กันบนเคาน์เตอร์หินอ่อน ฉากหลังเป็นสวนหินและต้นสนดัด",
      zh: "大理石台面上的木盒里排满一行行橙色海胆，后方是石头造景",
    },
  },
  {
    file: "/photos/66f4b170541c.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 5,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Wagyu tataki"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Chef uses tweezers to place a flower on thin seared beef slices on a black pedestal plate",
      th: "เชฟใช้ที่คีบวางดอกไม้กินได้ลงบนเนื้อย่างสไลซ์บางราดซอส จัดในจานสีดำทรงมีขา",
      zh: "厨师用镊子将一朵花放在黑色高脚盘中的炙烤牛肉薄片上",
    },
  },
  {
    file: "/photos/6bc8d2e712c9.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Wagyu tataki"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Seared wagyu slices on a wire rack over sliced onion and a bamboo leaf in a black ceramic bowl",
      th: "เนื้อวากิวย่างหั่นแว่น วางบนตะแกรงเหล็ก มีหอมใหญ่ซอยและใบไผ่รองอยู่ในชามเซรามิกสีดำ",
      zh: "黑色陶碗中，炙烤和牛片放在铁丝架上，下方是洋葱片和竹叶",
    },
  },
  {
    file: "/photos/71af8b4ee438.jpg",
    category: "food",
    hasPeople: false,
    warmth: 4,
    quality: 8,
    orientation: "portrait",
    dishMatches: ["Uni"],
    bestUse: "counter",
    source: "instagram",
    alt: {
      en: "Wooden trays of fresh sea urchin lined up along a white marble sushi counter",
      th: "กล่องไม้ใส่หอยเม่นสดเรียงยาวไปตามเคาน์เตอร์ซูชิหินอ่อนสีขาว",
      zh: "白色大理石寿司吧台上一字排开的木盒新鲜海胆",
    },
  },
  {
    file: "/photos/7344e12b9637.jpg",
    category: "people",
    hasPeople: true,
    warmth: 9,
    quality: 8,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "instagram",
    alt: {
      en: "A family of four smiling at the sushi counter with the chef standing behind them",
      th: "ครอบครัวสี่คนยิ้มให้กล้องที่เคาน์เตอร์ซูชิ โดยมีเชฟยืนอยู่ด้านหลัง",
      zh: "一家四口在寿司吧台前微笑，厨师站在他们身后",
    },
  },
  {
    file: "/photos/440ff65fffc2.jpg",
    category: "interior",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Curved marble omakase counter with blue velvet chairs, a blue noren curtain and painted wall murals",
      th: "เคาน์เตอร์โอมากาเสะหินอ่อนโค้ง เก้าอี้กำมะหยี่สีน้ำเงิน ผ้าโนเรนสีน้ำเงิน และภาพวาดบนผนัง",
      zh: "弧形大理石 Omakase 吧台，配蓝色丝绒座椅、蓝色暖帘和手绘壁画",
    },
  },
  {
    file: "/photos/17dd4959b0e0.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Zuwai kani"],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Shredded crab meat and orange roe in a crab shell, set in a dark bowl with pebbles and a flower",
      th: "เนื้อปูฉีกในกระดองปู โรยไข่ปลาสีส้ม จัดวางในชามเซรามิกสีเข้มที่ใส่กรวดและดอกไม้",
      zh: "蟹壳中盛着蟹肉丝和橙色鱼籽，置于深色碗中，碗里有卵石和一朵花",
    },
  },
  {
    file: "/photos/1f365022e967.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Fine-dine amadai"],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "White fish with crisp standing scales on a grilled lemon slice with orange sauce and edible flowers",
      th: "ปลาเนื้อขาวทอดเกล็ดกรอบ วางบนเลมอนย่าง ราดซอสสีส้ม ตกแต่งด้วยดอกไม้กินได้",
      zh: "鳞片酥脆竖立的白身鱼，放在烤柠檬片上，配橙色酱汁和食用花",
    },
  },
  {
    file: "/photos/269a79f26751.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Two seared salmon slices on shiso leaves with salmon roe and wasabi on a black plate",
      th: "แซลมอนย่างผิวสองชิ้นวางบนใบชิโสะ เสิร์ฟกับไข่ปลาแซลมอนและวาซาบิบนจานสีดำ",
      zh: "黑色盘中两片炙烤三文鱼，垫着紫苏叶，配三文鱼籽和山葵",
    },
  },
  {
    file: "/photos/fce7f6dd87bd.jpg",
    category: "food",
    hasPeople: true,
    warmth: 4,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Wagyu Sun"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Gloved hand holds a black dish with a wagyu round wrapped around a cured egg yolk topped with caviar",
      th: "มือเชฟสวมถุงมือสีดำยื่นจานเซรามิกสีดำ บนจานเป็นเนื้อวากิวห่อไข่แดงดอง โรยคาเวียร์ด้านบน",
      zh: "戴手套的手托着黑色餐盘，盘中一块圆形和牛包裹着腌渍蛋黄，顶上放着鱼子酱",
    },
  },
  {
    file: "/photos/a482957b80d2.jpg",
    category: "food",
    hasPeople: false,
    warmth: 5,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Botan ebi sushi", "Ama ebi sushi"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Chef brushing sauce onto a large prawn nigiri, its head and shell propped up beside the rice",
      th: "เชฟใช้แปรงทาซอสลงบนซูชิกุ้งตัวใหญ่ โดยมีหัวและเปลือกกุ้งตั้งไว้ข้างๆ บนจานสีขาว",
      zh: "厨师为大虾握寿司刷上酱汁，虾头和虾壳立在米饭旁",
    },
  },
  {
    file: "/photos/ab49be628b6e.jpg",
    category: "food",
    hasPeople: false,
    warmth: 4,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Wagyu"],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Close-up of a cut of beef being seared by blowtorch flame on a hot metal plate",
      th: "ภาพระยะใกล้ของเนื้อวากิวที่กำลังถูกไฟจากหัวพ่นไฟลนบนแผ่นเหล็กร้อน",
      zh: "特写：喷枪火焰正在炙烤热铁板上的一块牛肉",
    },
  },
  {
    file: "/photos/8fba7190a1e6.jpg",
    category: "food",
    hasPeople: false,
    warmth: 4,
    quality: 8,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "counter",
    source: "archive",
    alt: {
      en: "Raw fish course with fanned cucumber, ikura and wasabi on dark ceramic plates along the sushi counter.",
      th: "จานปลาดิบวางเรียงตามเคาน์เตอร์ซูชิ มีแตงกวาสไลซ์จัดเป็นพัด ไข่ปลาแซลมอน และวาซาบิ",
      zh: "寿司吧台上一排深色陶盘，盛着生鱼料理，配扇形黄瓜片、三文鱼籽和山葵",
    },
  },
  {
    file: "/photos/90264c6dbb2d.jpg",
    category: "signage",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "after-dark",
    source: "archive",
    alt: {
      en: "Lit Suan Zen Omakase pole sign at night, with the restaurant's wooden fence and building behind it.",
      th: "ป้ายไฟ Suan Zen Omakase ริมถนนตอนกลางคืน ด้านหลังเป็นรั้วไม้และตัวร้าน",
      zh: "夜间亮灯的 Suan Zen Omakase 立柱招牌，后方是餐厅的木栅栏和建筑",
    },
  },
  {
    file: "/photos/9306a6431f10.jpg",
    category: "food",
    hasPeople: true,
    warmth: 6,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Hands placing a small round baked cake in parchment paper tied with a red ribbon on a wooden board.",
      th: "มือกำลังวางเค้กชิ้นกลมในกระดาษรองผูกริบบิ้นแดงบนจานไม้",
      zh: "双手将一个圆形小烤蛋糕放到木板上，蛋糕包着烘焙纸，系着红丝带",
    },
  },
  {
    file: "/photos/b691eb59a482.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "portrait",
    dishMatches: ["Matcha mousse with crumble"],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Round matcha mousse cake on a dark crumble base, on a wooden tray with a gold spoon beside it.",
      th: "เค้กมูสชาเขียวทรงกลมบนฐานครัมเบิลสีเข้ม วางบนถาดไม้ มีช้อนสีทองวางข้าง ๆ",
      zh: "深色酥粒底的圆形抹茶慕斯蛋糕，放在木托盘上，旁边有一把金色勺子",
    },
  },
  {
    file: "/photos/c6640401024e.jpg",
    category: "food",
    hasPeople: true,
    warmth: 5,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Sashimi"],
    bestUse: "after-dark",
    source: "archive",
    alt: {
      en: "Gloved hands use tweezers to place a flower on sashimi arranged in an amber glass plate.",
      th: "มือสวมถุงมือสีดำใช้แหนบวางดอกไม้ลงบนซาชิมิในจานแก้วสีอำพัน",
      zh: "戴手套的双手用镊子在琥珀色玻璃盘里摆好的刺身上放一朵花",
    },
  },
  {
    file: "/photos/cac0b51e64fe.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: ["Wagyu"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Two slices of seared wagyu on a bamboo leaf with wasabi, pink salt and lime, on a white petal plate.",
      th: "เนื้อวากิวย่างสองชิ้นวางบนใบไผ่ เสิร์ฟกับวาซาบิ เกลือสีชมพู และมะนาวฝาน บนจานขาวทรงกลีบดอกไม้",
      zh: "白色花瓣形盘中，竹叶上放着两片炙烤和牛，配山葵、粉红盐和青柠",
    },
  },
  {
    file: "/photos/ea8212d3faff.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 6,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "A hand places edible flowers with tweezers beside a pale set dessert and crumble on a blue speckled plate.",
      th: "มือใช้แหนบวางดอกไม้กินได้ ข้างขนมเนื้อครีมสีขาวและครัมเบิล บนจานเซรามิกสีน้ำเงิน",
      zh: "一只手用镊子在蓝色斑点盘上摆放食用花，旁边是浅色冻状甜品和酥粒",
    },
  },
  {
    file: "/photos/ee3160d17d48.jpg",
    category: "food",
    hasPeople: true,
    warmth: 6,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Two pairs of hands hold a gold-rimmed plate of shellfish meat with lemon, marigold and orange sauce.",
      th: "สองมือประคองจานขอบทองที่มีเนื้ออาหารทะเล เสิร์ฟกับมะนาวฝาน ดอกไม้ และซอสสีส้ม",
      zh: "两双手端着金边餐盘，盘中是海鲜肉，配柠檬、万寿菊和橙色酱汁",
    },
  },
  {
    file: "/photos/f61f916d4040.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 8,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Crab shell of shredded crab meat topped with orange roe, in a dark pebble-filled bowl with a white flower.",
      th: "กระดองปูใส่เนื้อปูฉีกโรยไข่ปลาสีส้ม วางบนกรวดในชามสีเข้ม ประดับดอกไม้สีขาว",
      zh: "蟹壳里盛着蟹肉丝，上面铺着橙色鱼籽，置于铺满卵石的深色碗中，配一朵白花",
    },
  },
  {
    file: "/photos/95d9b8ba471b.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "square",
    dishMatches: [],
    bestUse: "course-card",
    source: "archive",
    alt: {
      en: "Scallop with yellow sauce and salmon roe on rice in a nori wrap, on a frosted glass plate.",
      th: "หอยเชลล์ราดซอสสีเหลือง โรยไข่ปลาแซลมอน วางบนข้าวห่อสาหร่าย เสิร์ฟบนจานแก้วฝ้า",
      zh: "磨砂玻璃盘上，海苔包着米饭，上面放着帆立贝、黄色酱汁和三文鱼籽",
    },
  },
  {
    file: "/photos/99d1e74b1c9c.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 8,
    orientation: "portrait",
    dishMatches: ["Uni"],
    bestUse: "counter",
    source: "archive",
    alt: {
      en: "Wooden trays of fresh sea urchin on a marble counter, with a bonsai and moss garden behind.",
      th: "ลังไม้ใส่หอยเม่นสดวางเรียงบนเคาน์เตอร์หินอ่อน ด้านหลังเป็นสวนมอสและต้นบอนไซ",
      zh: "大理石台面上的木盒新鲜海胆，后方是盆景和苔藓造景",
    },
  },
  {
    file: "/photos/09722e03bfec.jpg",
    category: "food",
    hasPeople: false,
    warmth: 1,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Seared beef roll around a raw egg yolk, topped with caviar and spring onion, on a dark plate",
      th: "เนื้อย่างม้วนเป็นวงล้อมไข่แดงดิบ ราดด้วยคาเวียร์และต้นหอมซอย วางบนจานสีเข้มพร้อมแผ่นกรอบและซอสสีดำ",
      zh: "深色盘中的炙烤牛肉卷，裹着生蛋黄，顶上放着鱼子酱和葱花",
    },
  },
  {
    file: "/photos/5138120a936b.jpg",
    category: "food",
    hasPeople: true,
    warmth: 5,
    quality: 7,
    orientation: "portrait",
    dishMatches: ["Uni handroll"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "A hand holding a nori hand roll filled with sea urchin, topped with caviar and wasabi.",
      th: "มือถือแฮนด์โรลสาหร่ายใส่หอยเม่น โรยคาเวียร์และวาซาบิด้านบน",
      zh: "一只手拿着海苔手卷，里面是海胆，顶上放着鱼子酱和山葵",
    },
  },
  {
    file: "/photos/27af6b0044e7.jpg",
    category: "people",
    hasPeople: true,
    warmth: 9,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "instagram",
    alt: {
      en: "Two guests and a chef in the dining room, smiling behind a large pink and white flower bouquet",
      th: "แขกสองคนกับเชฟยืนยิ้มถือช่อดอกไม้สีชมพูขาวช่อใหญ่ในร้าน",
      zh: "用餐区内，两位客人和一位厨师站在一大束粉白相间的花束后微笑",
    },
  },
  {
    file: "/photos/365dbb1ce96e.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Tuna nigiri topped with sea urchin roe and black caviar on a pale stone counter.",
      th: "ซูชิหน้าปลาทูน่าเนื้อแดง วางไข่หอยเม่นและคาเวียร์ดำไว้ด้านบน ตั้งอยู่บนเคาน์เตอร์หิน",
      zh: "浅色石质台面上的金枪鱼握寿司，顶上放着海胆和黑鱼子酱",
    },
  },
  {
    file: "/photos/774005717ee8.jpg",
    category: "people",
    hasPeople: true,
    warmth: 9,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "instagram",
    alt: {
      en: "Five smiling guests and the chef give thumbs up in front of the lit Suan Zen Omakase sign.",
      th: "กลุ่มลูกค้าถ่ายรูปกับเชฟหน้าป้ายไฟโลโก้ร้าน ทุกคนยิ้มและชูนิ้วโป้ง",
      zh: "五位客人和厨师在亮灯的 Suan Zen Omakase 招牌前微笑，竖起大拇指",
    },
  },
  {
    file: "/photos/5f578e092628.jpg",
    category: "people",
    hasPeople: true,
    warmth: 9,
    quality: 7,
    orientation: "square",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "facebook",
    alt: {
      en: "Family of five smiling at the sushi counter, two holding jasmine garlands, garden seen through glass",
      th: "ครอบครัวห้าคนนั่งเรียงกันที่เคาน์เตอร์ซูชิ ยิ้มให้กล้อง สองคนถือพวงมาลัยดอกมะลิ ด้านหลังเป็นสวนญี่ปุ่นหลังกระจก",
      zh: "一家五口在寿司吧台前微笑，其中两人手持茉莉花环，透过玻璃可见庭院",
    },
  },
  {
    file: "/photos/37a1d0f237df.jpg",
    category: "food",
    hasPeople: true,
    warmth: 6,
    quality: 7,
    orientation: "portrait",
    dishMatches: ["Wagyu yakiniku"],
    bestUse: "dish-hover",
    source: "archive",
    alt: {
      en: "Sliced grilled wagyu on a stone plate with broccoli, carrot and mushroom, more plates along the counter",
      th: "เนื้อวากิวย่างหั่นชิ้นวางบนจานหินพร้อมบร็อคโคลี แครอท และเห็ด เรียงต่อกันไปตามเคาน์เตอร์",
      zh: "石板上的烤和牛片，配西兰花、胡萝卜和蘑菇，吧台上还摆着更多餐盘",
    },
  },
  {
    file: "/photos/38ff80cea090.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 8,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "instagram",
    alt: {
      en: "Chef in a grey jacket standing with a smiling guest in front of the backlit Suan Zen logo at the entrance",
      th: "เชฟในเสื้อกุ๊กสีเทายืนถ่ายรูปกับลูกค้าหน้าโลโก้ Suan Zen ที่ผนังไม้ทางเข้าร้าน",
      zh: "身穿灰色上衣的厨师与一位微笑的客人站在入口处背光照明的 Suan Zen 标志前",
    },
  },
  {
    file: "/photos/90c15a8c6bb5.jpg",
    category: "people",
    hasPeople: true,
    warmth: 9,
    quality: 7,
    orientation: "square",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "facebook",
    alt: {
      en: "Seven guests posing together at the counter, three of them holding Thai jasmine garlands.",
      th: "ลูกค้าเจ็ดคนถ่ายรูปหมู่ที่เคาน์เตอร์ บางคนถือพวงมาลัยดอกมะลิ",
      zh: "七位客人在吧台前合影，其中三人手持泰式茉莉花环",
    },
  },
  {
    file: "/photos/f7a436a6e9ed.jpg",
    category: "food",
    hasPeople: false,
    warmth: 3,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "gallery",
    source: "instagram",
    alt: {
      en: "Molded custard dessert in orange sauce with edible flowers, a jasmine garland and crane wall mural behind.",
      th: "ขนมเนื้อคัสตาร์ดในซอสสีส้ม ประดับดอกไม้ ด้านหลังมีพวงมาลัยมะลิและผนังไม้ลายนกกระเรียน",
      zh: "橙色酱汁中的倒模蛋奶冻，点缀食用花，后方是茉莉花环和仙鹤壁画",
    },
  },
  {
    file: "/photos/9cac501b1874.jpg",
    category: "chef",
    hasPeople: true,
    warmth: 6,
    quality: 7,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "hero",
    source: "archive",
    alt: {
      en: "Chef searing seafood with a blowtorch over a small charcoal grill at the counter, flame rising.",
      th: "เชฟใช้ไฟพ่นย่างอาหารทะเลบนเตาถ่านเล็กที่เคาน์เตอร์ เปลวไฟลุกสูง",
      zh: "厨师在吧台的小炭炉上用喷枪炙烤海鲜，火焰升起",
    },
  },
  {
    file: "/photos/8d522dab888f.jpg",
    category: "food",
    hasPeople: false,
    warmth: 5,
    quality: 6,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Caramel custard in a brown-rimmed bowl with a pink flower, beside a jasmine garland on a stand.",
      th: "พุดดิ้งคาราเมลในถ้วยขอบน้ำตาล แต่งดอกไม้สีชมพู วางข้างพวงมาลัยมะลิบนขาตั้ง ฉากหลังลายนกกระเรียน",
      zh: "棕边碗中的焦糖布丁，点缀一朵粉色的花，旁边的架子上有茉莉花环",
    },
  },
  {
    file: "/photos/00524b6b30ad.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Rows of rectangular plates on a prep counter, each with baby squid in dark sauce and a yellow flower",
      th: "จานสี่เหลี่ยมเรียงเป็นแถวบนเคาน์เตอร์เตรียมอาหาร แต่ละจานมีปลาหมึกตัวเล็กราดซอสสีเข้ม วางคู่ดอกเบญจมาศเหลืองและใบไม้",
      zh: "备餐台上一排排长方形盘子，每盘都有淋着深色酱汁的小鱿鱼和一朵黄色的花",
    },
  },
  {
    file: "/photos/4a906697f15e.jpg",
    category: "food",
    hasPeople: true,
    warmth: 6,
    quality: 6,
    orientation: "square",
    dishMatches: ["Ama ebi sushi", "Botan ebi sushi"],
    bestUse: "gallery",
    source: "facebook",
    alt: {
      en: "Raw sweet shrimp heads standing upright on a sushi plate, with diners blurred behind the counter.",
      th: "หัวกุ้งดิบตั้งขึ้นบนจานซูชิ ด้านหลังเป็นแขกนั่งอยู่ริมเคาน์เตอร์แบบเบลอ ๆ",
      zh: "寿司盘上竖立着生甜虾头，背景是吧台边模糊的食客",
    },
  },
  {
    file: "/photos/2dc2687c3de2.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Torched glazed fish on a slice of white bread topped with salmon roe, on a shiso leaf",
      th: "ปลาย่างไฟราดซอส วางบนขนมปังขาว โรยไข่ปลาแซลมอนและต้นหอม บนใบชิโสะ",
      zh: "紫苏叶上放着一片白面包，面包上是刷酱炙烤的鱼肉，顶上放着三文鱼籽",
    },
  },
  {
    file: "/photos/331c65656530.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Rice porridge topped with salmon roe, spring onion and fried garlic in a patterned ceramic bowl.",
      th: "โจ๊กในชามเซรามิกลายเส้น โรยไข่ปลาแซลมอน ต้นหอมซอย และกระเทียมเจียว วางบนจานรองพร้อมช้อน",
      zh: "花纹陶瓷碗中的米粥，上面放着三文鱼籽、葱花和炸蒜",
    },
  },
  {
    file: "/photos/376fc5480825.jpg",
    category: "food",
    hasPeople: true,
    warmth: 5,
    quality: 6,
    orientation: "square",
    dishMatches: ["Sashimi"],
    bestUse: "counter",
    source: "facebook",
    alt: {
      en: "Two plates of seared salmon sashimi with salmon roe and greens on a sushi counter, citrus behind.",
      th: "ซาชิมิแซลมอนย่างไฟสองจานวางบนเคาน์เตอร์ซูชิ มีไข่ปลาแซลมอนและผักเคียง ด้านหลังมีเลมอนกับมะนาวเขียว",
      zh: "寿司吧台上两盘炙烤三文鱼刺身，配三文鱼籽和绿叶菜，后方有柑橘",
    },
  },
  {
    file: "/photos/7a499d55cbba.jpg",
    category: "people",
    hasPeople: true,
    warmth: 9,
    quality: 6,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "instagram",
    alt: {
      en: "Family of five posing behind a birthday cake with lit candles at a table beside the garden windows.",
      th: "ครอบครัวห้าคนถ่ายรูปหลังเค้กวันเกิดที่จุดเทียนอยู่ ริมกระจกที่มองเห็นสวนด้านนอก",
      zh: "一家五口在庭院窗边的餐桌旁合影，面前是点着蜡烛的生日蛋糕",
    },
  },
  {
    file: "/photos/5e288e7be59e.jpg",
    category: "people",
    hasPeople: true,
    warmth: 8,
    quality: 6,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "instagram",
    alt: {
      en: "Guests along the omakase counter watch a chef work; one holds up a phone to photograph the food",
      th: "แขกนั่งเรียงกันที่เคาน์เตอร์โอมากาเสะ มองเชฟเตรียมอาหารอยู่ด้านหลังเคาน์เตอร์ คนหนึ่งยกมือถือขึ้นถ่ายรูป",
      zh: "Omakase 吧台边的客人看着厨师操作，其中一人举起手机拍摄菜品",
    },
  },
  {
    file: "/photos/661acb502e4f.jpg",
    category: "food",
    hasPeople: false,
    warmth: 4,
    quality: 6,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Chopsticks placing gold leaf onto salmon roe in a small wooden bowl with tiny edible flowers",
      th: "ตะเกียบคีบทองคำเปลววางลงบนไข่ปลาแซลมอนในถ้วยไม้ใบเล็ก โรยดอกไม้กินได้",
      zh: "筷子将金箔放到小木碗中的三文鱼籽上，碗中点缀着细小的食用花",
    },
  },
  {
    file: "/photos/42a586ebc854.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Raw shrimp nigiri topped with grated cured egg yolk, shrimp head standing behind on a white plate",
      th: "ซูชิกุ้งดิบโรยไข่แดงดองขูดฝอย มีหัวกุ้งตั้งอยู่ด้านหลังบนจานเซรามิกสีขาว",
      zh: "白色盘中的生虾握寿司，上面撒着腌渍蛋黄碎，虾头立在后方",
    },
  },
  {
    file: "/photos/a86260877be7.jpg",
    category: "exterior",
    hasPeople: false,
    warmth: 3,
    quality: 6,
    orientation: "landscape",
    dishMatches: [],
    bestUse: "after-dark",
    source: "archive",
    alt: {
      en: "Suan Zen's lit yellow street sign and wooden restaurant building at dusk, seen from the car park",
      th: "ป้ายไฟสีเหลืองของร้าน Suan Zen และตัวอาคารไม้ในช่วงหัวค่ำ มองจากลานจอดรถ",
      zh: "黄昏时从停车场望去，Suan Zen 亮灯的黄色路边招牌和木质餐厅建筑",
    },
  },
  {
    file: "/photos/af2e9571bac6.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "portrait",
    dishMatches: ["Foie gras designed by Suan Zen"],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Seared foie gras on grains with orange roe and caviar, with orange, kiwi and a yellow flower",
      th: "ฟัวกราส์ย่างวางบนธัญพืช โรยไข่ปลาสีส้มและคาเวียร์ดำ เสิร์ฟคู่กับส้ม กีวี และดอกเบญจมาศสีเหลืองบนจานขอบทอง",
      zh: "谷物上的香煎鹅肝，配橙色鱼籽和鱼子酱，另有橙子、猕猴桃和一朵黄色的花",
    },
  },
  {
    file: "/photos/e2d46173b8ac.jpg",
    category: "people",
    hasPeople: true,
    warmth: 8,
    quality: 6,
    orientation: "square",
    dishMatches: [],
    bestUse: "people-warmth",
    source: "facebook",
    alt: {
      en: "Guests seated at the sushi counter at night, with dessert plates being finished in the foreground.",
      th: "ลูกค้านั่งที่เคาน์เตอร์ซูชิในช่วงค่ำ ด้านหน้ามีการจัดของหวานอยู่บนถาดไม้",
      zh: "夜晚，客人坐在寿司吧台前，前景中的甜品正在完成装盘",
    },
  },
  {
    file: "/photos/f26846b90108.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "portrait",
    dishMatches: [],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Crab shell filled with rice, crab meat and orange roe, set in a stone-filled bowl with yellow chrysanthemums.",
      th: "กระดองปูใส่ข้าว เนื้อปู และไข่ปลาสีส้ม วางในชามกรวด ประดับดอกเบญจมาศสีเหลือง",
      zh: "蟹壳中盛着米饭、蟹肉和橙色鱼籽，置于铺满石子的碗中，配黄色菊花",
    },
  },
  {
    file: "/photos/9962feecc2f7.jpg",
    category: "food",
    hasPeople: false,
    warmth: 2,
    quality: 6,
    orientation: "portrait",
    dishMatches: ["Uni"],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "A row of wooden uni trays along a marble counter, beside a wood wall painted with a tree.",
      th: "ลังไม้ใส่อุนิเรียงยาวไปตามเคาน์เตอร์หินอ่อน ข้างผนังไม้ที่มีภาพวาดต้นไม้",
      zh: "大理石台面上一排木盒海胆，旁边是绘有一棵树的木墙",
    },
  },
  {
    file: "/photos/b63e98c7df99.jpg",
    category: "food",
    hasPeople: true,
    warmth: 4,
    quality: 5,
    orientation: "landscape",
    dishMatches: ["Sashimi"],
    bestUse: "gallery",
    source: "archive",
    alt: {
      en: "Slices of seared and raw fish on a dark ceramic plate with salmon roe, wasabi and a yellow chrysanthemum.",
      th: "ปลาดิบและปลาย่างวางบนจานเซรามิกสีเข้ม มีไข่ปลาแซลมอน วาซาบิ และดอกเบญจมาศสีเหลือง",
      zh: "深色陶盘中的炙烤鱼片和生鱼片，配三文鱼籽、山葵和一朵黄色菊花",
    },
  },
];

/** The pictures with people in them — the ones the room is actually about. */
export const peopleShots = photos
  .filter((p) => p.hasPeople || p.warmth >= 7)
  .sort((a, b) => b.warmth * b.quality - a.warmth * a.quality);

export const foodShots = photos.filter((p) => p.category === "food" || p.category === "detail");
export const roomShots = photos.filter((p) => p.category === "interior" || p.category === "exterior" || p.category === "signage");

export const byFile = (f: string) => photos.find((p) => p.file === f || p.file.endsWith("/" + f));

/** Photographs that show a given dish, best first. */
export const shotsForDish = (dish: string) =>
  photos
    .filter((p) => p.dishMatches.some((d) => d.toLowerCase() === dish.toLowerCase()))
    .sort((a, b) => b.quality - a.quality);
